# Generated by Django 5.0.7 on 2024-08-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='year_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
