# Generated by Django 5.0.7 on 2024-08-01 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0002_animemodel_year_of_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('year_of_issue', models.DateField(blank=True, null=True)),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.charactermodel')),
            ],
        ),
    ]
