# Generated by Django 5.1.3 on 2024-12-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_characters_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_characters_app.sectionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WikiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('community_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_characters_app.postmodel')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_characters_app.sectionmodel')),
            ],
        ),
    ]
