# Generated by Django 5.1.3 on 2024-12-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_characters_app', '0002_sectionmodel_postmodel_wikimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='image',
            field=models.ImageField(upload_to='section_images/'),
        ),
        migrations.AlterField(
            model_name='wikimodel',
            name='community_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb_characters_app.postmodel'),
        ),
    ]
