# Generated by Django 5.1.3 on 2024-12-05 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_characters_app', '0003_alter_sectionmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
