# Generated by Django 5.1.3 on 2024-12-05 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_characters_app', '0006_alter_sectionmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
