# Generated by Django 5.1.3 on 2024-12-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_characters_app', '0010_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='is_like',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
