# Generated by Django 5.1.3 on 2024-12-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_characters_app', '0011_alter_commentreaction_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreaction',
            name='is_dislike',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
